name: CI - Unit Tests

on: [push]

jobs:
  build:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 44646:3306

    strategy:
      matrix:
        java: [8, 9, 10, 11]

    runs-on: ubuntu-latest

    name: Ubuntu (Java ${{ matrix.java }})
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK (Java ${{ matrix.java }})
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Set up Gradle permissions
        run: chmod +x gradlew

      - name: Build Gradle project
        run: ./gradlew check --info --stacktrace
        env:
          TEST_MYSQL_SERVER: 127.0.0.1
          TEST_MYSQL_PORT: 44646
          TEST_MYSQL_USER: root
          TEST_MYSQL_PASSWORD: password
          JETWAY_STDOUT_LOG_LEVEL: OFF
